import type { GuestRecord } from "@/lib/attendance-types"

export const seedGuests: GuestRecord[] = [
  {
    invitationNumber: "A-001",
    fullName: "Dr. Apt. Salmah Orbaniyah, MKes",
    organization: "AISYIYAH",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-002",
    fullName: "Tri Yulianti Setyasari, S.Sn",
    organization: "WANITA TAMAN SISWA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-003",
    fullName: "Elly Kusumawati Handoko",
    organization: "WANITA KATHOLIK REPUBLIK INDONESIA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-004",
    fullName: "Hj. Wien Yoyo S",
    organization: "PASUNDAN ISTERI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-005",
    fullName: "Prof. Dewi Indriani Yusuf",
    organization: "PERWARI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-006",
    fullName: "Pdt. Detty BT Liow Mambo, STh",
    organization: "PERSATUAN WANITA KRISTEN INDONESIA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-007",
    fullName: "Ir. R. Ay . Endang W. Rama Boedi, MSc",
    organization: "PUTRI NARPO WANDOWO",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-008",
    fullName: "Dra. Damayanti Soetjahjo",
    organization: "BUDI ISTERI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-010",
    fullName: "Novia H Lambey SS",
    organization: "PIKAT",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-011",
    fullName: "Hj. Rosa Muhammad Bsc, S.Pd",
    organization: "PERWANAS",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-012",
    fullName: "Tati Subandi",
    organization: "PWK-UGM",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-013",
    fullName: "Dr. Ade Jubaedah , S.Keb.Bdn,MM.MKM",
    organization: "IKATAN BIDAN INDONESIA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-016",
    fullName: "Femmy Pangkerego S.E. M.Pd",
    organization: "WANITA SAHATI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-017",
    fullName: "Prof.Dr. Hj. Valina Singka Subekti, M.Si",
    organization: "WANITA SYARIKAT ISLAM",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-018",
    fullName: "Murbawi Siwi, SKM",
    organization: "RUKUN WANITA INDONESIA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-019",
    fullName: "Arifatul Choiri Fauzi",
    organization: "MUSLIMAT NU",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-020",
    fullName: "Titi Suwarso",
    organization: "PERSATUAN ISTERI TEKNISI INDONESIA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-021",
    fullName: "DR Ir. Giwo Rubianto Wiyogo",
    organization: "GERAKAN WANITA SEJAHTERA (GWS)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-022",
    fullName: "Dr. Ir. Retno Sri Endah Lestari, MSc.PhD",
    organization: "IKATAN SARJANA WANITA INDONESIA (ISWI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-028",
    fullName: "",
    organization: "IKATAN KELUARGA WARTAWAN INDONESIA (IKWI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-031",
    fullName: "Usanti Sindia A. Permana",
    organization: "IKATAN ISTERI DOKTER INDONESIA (IIDI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-032",
    fullName: "Santi Diansari Hargianto, S.H, M.H",
    organization: "WANITA PERSAHI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-034",
    fullName: "Dra.Hj. Marfuah Musthofa,M.Pd",
    organization: "WANITA ISLAM",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-035",
    fullName: "Sri Meisista",
    organization: "KORPS HMI - WATI (KOHATI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-037",
    fullName: "Lina Indiarti Wresniwiro, SE.MM",
    organization: "PIVERI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-041",
    fullName: "Endah Ade Supandi",
    organization: "PERIP",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-044",
    fullName: "Ernawati Fauzi",
    organization: "WANITA KOSGORO",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-045",
    fullName: "Hj. Ening Thalhah",
    organization: "WANITA SATYAPRAJA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-046",
    fullName: "Siti Amelia Jorjiana, S.SN.MH",
    organization: "WANITA MKGR",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-047",
    fullName: "Dr. Rahayu Setya Wardani, SH.MH",
    organization: "KERTAWREDATAMA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-048",
    fullName: "Ir. Dyah Anita Prihapsari, MA",
    organization: "IWAPI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-049",
    fullName: "Dra. Asdirwati Ali MM",
    organization: "PERWATI WANITA PERTI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-050",
    fullName: "Ir. Anggraini Purnami",
    organization: "PERSATUAN ISTERI INSINYUR INDONESIA (PIII)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-052",
    fullName: "Hj. Netty Marliza Komarudin, S.H",
    organization: "WANITA SWADIRI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-054",
    fullName: "Ir. Dany Soedarsono",
    organization: "HIMPUNAN WANITA KARYA (HWK)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-055",
    fullName: "Brigjen TNI",
    organization: "DEPWAN PEPABRI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-056",
    fullName: "Ny. Venessa Supit",
    organization: "KARTINI AMPI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-057",
    fullName: "Prof. Dr. Unifah Rosyidi, M.Pd",
    organization: "WANITA PGRI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-058",
    fullName: "Dra. Anita Ariyani",
    organization: "WANITA TANI INDONESIA HKTI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-059",
    fullName: "Ny. Dr. Ir. Hetifah Sjaifudian, MPP",
    organization: "AL-HIDAYAH",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-060",
    fullName: "Ny. Lucy Salim",
    organization: "WANITA BUDDHIS INDONESIA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-061",
    fullName: "Dwie Riawenny Nasution",
    organization: "WANITA FKPPI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-062",
    fullName: "Ny. Yuliarti  R Merati",
    organization: "IKAI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-064",
    fullName: "Hj. Margaret Aliyatul Maimunah, SS.,MSi",
    organization: "FATAYAT NU",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-065",
    fullName: "Ny. Pia Feriasti Megananda, BA",
    organization: "WIRAWATI CATUR PANCA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-066",
    fullName: "Ny. Lana Trilli Naire Akademi",
    organization: "WANITA SHUFIAH",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-067",
    fullName: "Dra. Diah A. Hadi Daryanto",
    organization: "PERWITA WANA KENCANA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-069",
    fullName: "Wulan AS Sari",
    organization: "KOPPRI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-070",
    fullName: "Prof. Dr. Zahrotun Nihayah, M.Psi",
    organization: "GUPPI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-071",
    fullName: "Drh. Tri Isyani Tunggadewi, MSc",
    organization: "PIDHI MVI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-072",
    fullName: "Dr. dr. Hj. Ulla Nuchwaty, MM",
    organization: "WANITA PEMBANGUNAN INDONESIA (WPI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-073",
    fullName: "Ny. Dr, Hj. Hediati Erry",
    organization: "DPP WPPKBI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-074",
    fullName: "Ny. Dr. Hj. Marlinda Irwanti Poernomo, SE,M.Si",
    organization: "KORPS WANITA MDI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-075",
    fullName: "Dr. Ir. Anita Dewi Anggraini Kolopaking,SH.MH.FCBAr b",
    organization: "YATNAWATI KERTINI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-076",
    fullName: "Hj. Fifi Firman Gani",
    organization: "DIAN KEMALA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-077",
    fullName: "Reny Anggrayni",
    organization: "PERSAUDARAAN MUSLIMAH (SALIMAH)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-078",
    fullName: "Wikanti Yogi, S.Ag, MS",
    organization: "WANITA HINDU DHARMA INDONESIA (WHDI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-079",
    fullName: "Retno Multriarti",
    organization: "IKABOGA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-080",
    fullName: "Dr Evita Nursanty MSc",
    organization: "WANITA KBPPP POLRI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-081",
    fullName: "Ariati Dina Puspitasari",
    organization: "NASYIATUL AISYIYAH",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-082",
    fullName: "Ny. Dr. Hj. Marlinda Irwanti Poernomo, SE,M.Si",
    organization: "FORUM PEMBERDAYAAN PEREMPUAN INDONESIA (FPPI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-083",
    fullName: "Herliani, M.Ag",
    organization: "WANITA PUI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-084",
    fullName: "Ir. Rahayu Murdjaningsih",
    organization: "IISPI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-085",
    fullName: "Revita Alvi",
    organization: "HIMPUNAN WANITA DISABILITAS INDONESIA (HWDI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-086",
    fullName: "Free Heart",
    organization: "PERSATUAN WANITA PENULIS INDONESIA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-087",
    fullName: "M.M Sri Sumaryanti Budhisantoso",
    organization: "PEREMPUAN MANDIRI REPUBLIK INDONESIA (PMRI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-088",
    fullName: "Hj. Sarimaya, SE.MSi",
    organization: "SRIKANDI PEMUDA PANCASILA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-089",
    fullName: "E.K. Dewi Batubara, ST.M.Sos",
    organization: "PERGERAKAN SARINAH",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-090",
    fullName: "Hj. Ingrid Kansil S.Sos",
    organization: "IKATAN PENGUSAHA MUSLIMAH INDONESIA (IPEMI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-091",
    fullName: "Hj. Andi Nurhiyari Jamaro Dulung, M.Si",
    organization: "IKATAN WANITA SULAWESI SELATAN (IWSS)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-092",
    fullName: "Prof. Dr.Hj. Elza Syarief,SH.MH",
    organization: "PERKUMPULAN PEREMPUAN WIRAUSAHA INDONESIA (PERWIRA)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-093",
    fullName: "Ratieh Sanggarwati, S.E",
    organization: "KOMUNITAS IBU CERDAS INDONESIA (KICI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-094",
    fullName: "Dra.Hj. Indah Suryadharma Ali,MBA",
    organization: "PPLIPI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-095",
    fullName: "Dra. Hj. Nurliati Ahmad, MA",
    organization: "MUSLIMAT AL WASHLIYAH",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-096",
    fullName: "Hj. Trisna Ningsih Yuliati,SE",
    organization: "MUSLIMAT MATHLA'UL ANWAR",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-097",
    fullName: "bu Taty Toisuta-Leimena",
    organization: "PERSATUAN WANITA MALUKU INDONESIA (PERWAMA INA)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-098",
    fullName: "Hj. Rini Sujiyanti,SE.,MM",
    organization: "PERSATUAN SRIKANDI KREATIF INDONESIA (PERSIKINDO)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-099",
    fullName: "Veve Safitri",
    organization: "PEREMPUAN PEMIMPIN INDONESIA (PERPINA)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-100",
    fullName: "Linda Astuty, ST, MM",
    organization: "PERKUMPULAN KONTRAKTOR PERTIWI INDONESIA (PERKOPIN)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-101",
    fullName: "dr. Rosaline Irene Rumaseuw, M.Kes",
    organization: "CENDEKIAWAN PEREMPUAN PAPUA (CPP)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-102",
    fullName: "Hj. Ernawati Budin, B.BA",
    organization: "FORUM KOMUNIKASI IBU-IBU SUMATERA BAGIAN SELATAN (FKIISBS)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-103",
    fullName: "Dra. Hj. Saihun Aldjufrie, M.Pd.I",
    organization: "WANITA ISLAM ALKHAIRAT",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-104",
    fullName: "Lana T. Kuntjoro",
    organization: "PEREMPUAN INDONESIA MAJU (PIM)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-105",
    fullName: "Ir. Diah Indrajati, MSc",
    organization: "PEREMPUAN PENSIUNAN INDONESIA (PERPENI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-106",
    fullName: "Artika Kristanti",
    organization: "JALASTORIA",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-107",
    fullName: "Prof.Dr.Hj. Sylviana Murni, SH.MSi",
    organization: "MAJELIS ILMUWAN MUSLIMAH INDONESIA (MAI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-108",
    fullName: "Prof.Dr. Hj. Siti Nur Azizah, SH.M.Hum",
    organization: "PERHIMPUNAN SAUDAGAR MUSLIMAH INDONESIA (PERSAMI)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-109",
    fullName: "Hj. Melani Leimena Suharli, S.Sos.MM",
    organization: "PERKUMPULAN WANITA PEJUANG '45",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-110",
    fullName: "IJP",
    organization: "Paguyuban Keluarga Besar Purnawirawan Polisi Wanita (PKB PPRI-PP POLRI",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
  {
    invitationNumber: "A-111",
    fullName: "Hastuti Sari Sukapti , SH BrigadirJenderal TNI",
    organization: "PERSATUAN PURNAWIRAWAN KORPS WANITA ANGKATAN DARAT (PP KOWAD)",
    role: "Delegasi",
    attendanceStatus: "not_checked_in",
    checkedInAt: null,
  },
]
